version: '2'
services:
  sftp:
    image: atmoz/sftp
    ports:
     - "2022:22"
    volumes:
     - /tmp:/home/jetbrains/upload
     - ~/.ssh/id_rsa.pub:/home/jetbrains/.ssh/keys/id_rsa.pub:ro
    command: jetbrains:jetbrains:1001
  ftp:
    image: wildscamp/vsftpd
    volumes:
      - /tmp:/home/virtual/jetbrains/share
    environment:
      PASV_ADDRESS: 192.168.2.186
      VSFTPD_USER_1: "jetbrains:jetbrains::"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
  ftps:
    build: ./ftps
    volumes:
          - /tmp:/home/virtual/jetbrains/share
    environment:
      PASV_ADDRESS: 192.168.2.186
      VSFTPD_USER_1: "jetbrains:jetbrains::"
      PASV_MIN_PORT: 30010
      PASV_MAX_PORT: 30019
    ports:
      - "23:21"
      - "30010-30019:30010-30019"